#!/usr/bin/env bash
# Install a /usr/local/bin/binwalk wrapper that runs binwalk via docker.
#
# The image `devvmsetup/binwalk:local` is built locally from the
# ReFirmLabs/binwalk clone staged by git_sources (see vmconfig.yaml). If
# the tag is missing when this script runs, we build it here.
#
# Idempotent: rewrites the shim each run.
set -euo pipefail

IMAGE="devvmsetup/binwalk:local"
WRAPPER="/usr/local/bin/binwalk"
REPO_DIR="${HOME}/src/binwalk"

if ! command -v docker >/dev/null 2>&1; then
    echo "post/40-binwalk-wrapper: docker not installed; skipping" >&2
    exit 0
fi

# Talk to the docker daemon with the invoking user's creds when the
# socket is writable (i.e. user is in the docker group for this session);
# sudo otherwise.
docker_cmd() {
    if docker info >/dev/null 2>&1; then
        docker "$@"
    else
        sudo docker "$@"
    fi
}

if ! docker_cmd image inspect "$IMAGE" >/dev/null 2>&1; then
    if [[ -d "$REPO_DIR" ]]; then
        echo "post/40-binwalk-wrapper: building $IMAGE from $REPO_DIR"
        ( cd "$REPO_DIR" && docker_cmd build -t "$IMAGE" . )
    else
        echo "post/40-binwalk-wrapper: $IMAGE missing and $REPO_DIR not cloned" >&2
        echo "  run setup.py with git_sources enabled to clone ReFirmLabs/binwalk" >&2
        exit 1
    fi
fi

read -r -d '' SCRIPT <<EOF || true
#!/usr/bin/env bash
# Auto-generated by DevVMSetup. Runs the locally-built binwalk image.
exec docker run --rm \\
    --user "\$(id -u):\$(id -g)" \\
    -v "\$PWD":/work -w /work \\
    $IMAGE "\$@"
EOF

tmpfile="$(mktemp)"
printf '%s\n' "$SCRIPT" > "$tmpfile"
sudo install -m 0755 "$tmpfile" "$WRAPPER"
rm -f "$tmpfile"
echo "post/40-binwalk-wrapper: installed $WRAPPER -> $IMAGE"
