#!/usr/bin/env bash
# Install a /usr/local/bin/binwalk wrapper that runs the refirmlabs/binwalk docker image.
# Idempotent: rewrites the shim each run (cheap + keeps it fresh).
set -euo pipefail

IMAGE="refirmlabs/binwalk:latest"
WRAPPER="/usr/local/bin/binwalk"

if ! command -v docker >/dev/null 2>&1; then
    echo "post/40-binwalk-wrapper: docker not installed; skipping" >&2
    exit 0
fi

read -r -d '' SCRIPT <<'EOF' || true
#!/usr/bin/env bash
# Auto-generated by DevVMSetup. Runs the latest binwalk via docker.
exec docker run --rm \
    --user "$(id -u):$(id -g)" \
    -v "$PWD":/work -w /work \
    refirmlabs/binwalk:latest "$@"
EOF

tmpfile="$(mktemp)"
printf '%s\n' "$SCRIPT" > "$tmpfile"
sudo install -m 0755 "$tmpfile" "$WRAPPER"
rm -f "$tmpfile"
echo "post/40-binwalk-wrapper: installed $WRAPPER -> $IMAGE"
